// Detalles de los códigos para cada tarjeta
const cardCodeDetails = {
    "1": {
        code: `
          _id: ObjectId('66f3a3cb17bbfb4e9842f807'),
    id: 1,
    nombre: 'Arepas',
    descripcion: 'Tortillas de maíz, rellenas de queso, carne o huevo.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 15,
    calorias: 200,
    ingredientesPrincipales: 'Maíz, queso, carne',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 8
`
    },
    "2": {
        code: `
         _id: ObjectId('66f3a3ffced863da0142f808'),
    id: 2,
    nombre: 'Bandeja Paisa',
    descripcion: 'Plato tradicional con frijoles, arroz, carne, chicharrón y aguacate.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 800,
    ingredientesPrincipales: 'Frijoles, arroz, carne, chicharrón, aguacate',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f809'),
    id: 3,
    nombre: 'Ajiaco',
    descripcion: 'Sopa de pollo con papas y maíz, servida con crema y aguacate.',
    precio: 35000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 400,
    ingredientesPrincipales: 'Pollo, papas, maíz, crema, aguacate',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f80a'),
    id: 4,
    nombre: 'Sancocho',
    descripcion: 'Sopa de carne con yuca, plátano y maíz.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Carne, yuca, plátano, maíz',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f80d'),
    id: 7,
    nombre: 'Posta Negra Cartagenera',
    descripcion: 'Carne de res en salsa negra, acompañada de arroz y plátano.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 50,
    calorias: 600,
    ingredientesPrincipales: 'Carne de res, salsa negra',
    nivelPicante: 'Suave',
    disponibilidad: 10,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f810'),
    id: 10,
    nombre: 'Pargo frito',
    descripcion: 'Pescado frito, servido con arroz y ensalada.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 500,
    ingredientesPrincipales: 'Pargo, arroz, ensalada',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f812'),
    id: 12,
    nombre: 'Lechona',
    descripcion: 'Cerdo asado relleno de arroz, guisantes y especias.',
    precio: 60000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 120,
    calorias: 800,
    ingredientesPrincipales: 'Cerdo, arroz, guisantes',
    nivelPicante: 'Suave',
    disponibilidad: 10,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f814'),
    id: 14,
    nombre: 'Frijoles con Arracacha',
    descripcion: 'Frijoles cocidos con arracacha, acompañados de arroz.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 40,
    calorias: 350,
    ingredientesPrincipales: 'Frijoles, arracacha',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f815'),
    id: 15,
    nombre: 'Arroz con Pollo',
    descripcion: 'Arroz cocido con pollo y verduras, sazonado al gusto.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 450,
    ingredientesPrincipales: 'Arroz, pollo, verduras',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f816'),
    id: 16,
    nombre: 'Cocido Boyacense',
    descripcion: 'Sopa con carne, papa, yuca y plátano, típico de Boyacá.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Carne, papa, yuca, plátano',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f817'),
    id: 17,
    nombre: 'Pudín de pan',
    descripcion: 'Postre elaborado con pan, leche y huevo, al horno.',
    precio: 12000,
    categoria: 'Postres',
    tiempoPreparacion: 40,
    calorias: 300,
    ingredientesPrincipales: 'Pan, leche, huevo',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f818'),
    id: 18,
    nombre: 'Galletas de Arequipe',
    descripcion: 'Galletas rellenas de arequipe, un dulce tradicional.',
    precio: 5000,
    categoria: 'Postres',
    tiempoPreparacion: 15,
    calorias: 200,
    ingredientesPrincipales: 'Harina, arequipe',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f81b'),
    id: 21,
    nombre: 'Cocada',
    descripcion: 'Dulce de coco rallado y azúcar, típico de la región Caribe.',
    precio: 4000,
    categoria: 'Postres',
    tiempoPreparacion: 20,
    calorias: 150,
    ingredientesPrincipales: 'Coco, azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f81c'),
    id: 22,
    nombre: 'Buñuelos',
    descripcion: 'Dulces fritos de masa de queso, servidos calientes.',
    precio: 15000,
    categoria: 'Postres',
    tiempoPreparacion: 25,
    calorias: 250,
    ingredientesPrincipales: 'Queso, harina',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f821'),
    id: 27,
    nombre: 'Mazamorra',
    descripcion: 'Postre de maíz con leche, típico del interior de Colombia.',
    precio: 5000,
    categoria: 'Postres',
    tiempoPreparacion: 10,
    calorias: 250,
    ingredientesPrincipales: 'Maíz, leche, azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f822'),
    id: 28,
    nombre: 'Caldo de Costilla',
    descripcion: 'Sopa caliente de costilla de res con papas y especias.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 350,
    ingredientesPrincipales: 'Costilla de res, papa, especias',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f823'),
    id: 29,
    nombre: 'Tamal Santafereño',
    descripcion: 'Tamales elaborados con masa de maíz y varios rellenos, típicos de Bogotá.',
    precio: 18000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Maíz, carne, vegetales',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f824'),
    id: 30,
    nombre: 'Sudado de Pollo',
    descripcion: 'Pollo cocido en salsa con papas y yuca, acompañado de arroz.',
    precio: 25000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 40,
    calorias: 600,
    ingredientesPrincipales: 'Pollo, papas, yuca',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f825'),
    id: 31,
    nombre: 'Chontaduro con sal y miel',
    descripcion: 'Fruta tropical, servida con sal y miel.',
    precio: 10000,
    categoria: 'Postres',
    tiempoPreparacion: 5,
    calorias: 150,
    ingredientesPrincipales: 'Chontaduro, sal, miel',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f826'),
    id: 32,
    nombre: 'Arroz con Leche',
    descripcion: 'Postre cremoso de arroz cocido en leche con canela.',
    precio: 8000,
    categoria: 'Postres',
    tiempoPreparacion: 30,
    calorias: 300,
    ingredientesPrincipales: 'Arroz, leche, canela',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a3ffced863da0142f828'),
    id: 34,
    nombre: 'Arroz Atollado',
    descripcion: 'Arroz cremoso con cerdo, chorizo y papas, típico del Valle del Cauca.',
    precio: 35000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 50,
    calorias: 700,
    ingredientesPrincipales: 'Arroz, cerdo, chorizo, papas',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 9
`
    },
    "3": {
        code: `
            _id: ObjectId('66f3a5b0c8ef979fd042f808'),
    id: 2,
    nombre: 'Bandeja Paisa',
    descripcion: 'Plato tradicional con frijoles, arroz, carne, chicharrón y aguacate.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 800,
    ingredientesPrincipales: 'Frijoles, arroz, carne, chicharrón, aguacate',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f809'),
    id: 3,
    nombre: 'Ajiaco',
    descripcion: 'Sopa de pollo con papas y maíz, servida con crema y aguacate.',
    precio: 35000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 400,
    ingredientesPrincipales: 'Pollo, papas, maíz, crema, aguacate',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f80a'),
    id: 4,
    nombre: 'Sancocho',
    descripcion: 'Sopa de carne con yuca, plátano y maíz.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Carne, yuca, plátano, maíz',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f80b'),
    id: 5,
    nombre: 'Tamales',
    descripcion: 'Masa de maíz rellena de carne y verduras, cocida en hojas de plátano.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 90,
    calorias: 350,
    ingredientesPrincipales: 'Maíz, carne, verduras',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f80d'),
    id: 7,
    nombre: 'Posta Negra Cartagenera',
    descripcion: 'Carne de res en salsa negra, acompañada de arroz y plátano.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 50,
    calorias: 600,
    ingredientesPrincipales: 'Carne de res, salsa negra',
    nivelPicante: 'Suave',
    disponibilidad: 10,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f80e'),
    id: 8,
    nombre: 'Bollos',
    descripcion: 'Masa de maíz con queso, envuelta en hojas de plátano y cocida al vapor.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 30,
    calorias: 250,
    ingredientesPrincipales: 'Maíz, queso',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f810'),
    id: 10,
    nombre: 'Pargo frito',
    descripcion: 'Pescado frito, servido con arroz y ensalada.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 500,
    ingredientesPrincipales: 'Pargo, arroz, ensalada',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f812'),
    id: 12,
    nombre: 'Lechona',
    descripcion: 'Cerdo asado relleno de arroz, guisantes y especias.',
    precio: 60000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 120,
    calorias: 800,
    ingredientesPrincipales: 'Cerdo, arroz, guisantes',
    nivelPicante: 'Suave',
    disponibilidad: 10,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f814'),
    id: 14,
    nombre: 'Frijoles con Arracacha',
    descripcion: 'Frijoles cocidos con arracacha, acompañados de arroz.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 40,
    calorias: 350,
    ingredientesPrincipales: 'Frijoles, arracacha',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f815'),
    id: 15,
    nombre: 'Arroz con Pollo',
    descripcion: 'Arroz cocido con pollo y verduras, sazonado al gusto.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 450,
    ingredientesPrincipales: 'Arroz, pollo, verduras',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f816'),
    id: 16,
    nombre: 'Cocido Boyacense',
    descripcion: 'Sopa con carne, papa, yuca y plátano, típico de Boyacá.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Carne, papa, yuca, plátano',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f817'),
    id: 17,
    nombre: 'Pudín de pan',
    descripcion: 'Postre elaborado con pan, leche y huevo, al horno.',
    precio: 12000,
    categoria: 'Postres',
    tiempoPreparacion: 40,
    calorias: 300,
    ingredientesPrincipales: 'Pan, leche, huevo',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f819'),
    id: 19,
    nombre: 'Morcilla',
    descripcion: 'Embutido a base de sangre, arroz y especias.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 30,
    calorias: 250,
    ingredientesPrincipales: 'Sangre, arroz',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 5
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f81a'),
    id: 20,
    nombre: 'Tamal Tolimense',
    descripcion: 'Tamales de masa de maíz con carne, vegetales y especias.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 90,
    calorias: 400,
    ingredientesPrincipales: 'Maíz, carne, vegetales',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f822'),
    id: 28,
    nombre: 'Caldo de Costilla',
    descripcion: 'Sopa caliente de costilla de res con papas y especias.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 350,
    ingredientesPrincipales: 'Costilla de res, papa, especias',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f823'),
    id: 29,
    nombre: 'Tamal Santafereño',
    descripcion: 'Tamales elaborados con masa de maíz y varios rellenos, típicos de Bogotá.',
    precio: 18000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Maíz, carne, vegetales',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f824'),
    id: 30,
    nombre: 'Sudado de Pollo',
    descripcion: 'Pollo cocido en salsa con papas y yuca, acompañado de arroz.',
    precio: 25000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 40,
    calorias: 600,
    ingredientesPrincipales: 'Pollo, papas, yuca',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f826'),
    id: 32,
    nombre: 'Arroz con Leche',
    descripcion: 'Postre cremoso de arroz cocido en leche con canela.',
    precio: 8000,
    categoria: 'Postres',
    tiempoPreparacion: 30,
    calorias: 300,
    ingredientesPrincipales: 'Arroz, leche, canela',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f828'),
    id: 34,
    nombre: 'Arroz Atollado',
    descripcion: 'Arroz cremoso con cerdo, chorizo y papas, típico del Valle del Cauca.',
    precio: 35000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 50,
    calorias: 700,
    ingredientesPrincipales: 'Arroz, cerdo, chorizo, papas',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a5b0c8ef979fd042f829'),
    id: 35,
    nombre: 'Caldo de Mondongo',
    descripcion: 'Sopa espesa con mondongo (callos) y papas.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 500,
    ingredientesPrincipales: 'Mondongo, papas, especias',
    nivelPicante: 'Medio',
    disponibilidad: 15,
    popularidad: 7`
    },
    "4": {
        code: `
          _id: ObjectId('66f3a5f3855b708d4b42f809'),
    id: 3,
    nombre: 'Ajiaco',
    descripcion: 'Sopa de pollo con papas y maíz, servida con crema y aguacate.',
    precio: 35000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 400,
    ingredientesPrincipales: 'Pollo, papas, maíz, crema, aguacate',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a5f3855b708d4b42f80d'),
    id: 7,
    nombre: 'Posta Negra Cartagenera',
    descripcion: 'Carne de res en salsa negra, acompañada de arroz y plátano.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 50,
    calorias: 600,
    ingredientesPrincipales: 'Carne de res, salsa negra',
    nivelPicante: 'Suave',
    disponibilidad: 10,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a5f3855b708d4b42f810'),
    id: 10,
    nombre: 'Pargo frito',
    descripcion: 'Pescado frito, servido con arroz y ensalada.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 500,
    ingredientesPrincipales: 'Pargo, arroz, ensalada',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a5f3855b708d4b42f812'),
    id: 12,
    nombre: 'Lechona',
    descripcion: 'Cerdo asado relleno de arroz, guisantes y especias.',
    precio: 60000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 120,
    calorias: 800,
    ingredientesPrincipales: 'Cerdo, arroz, guisantes',
    nivelPicante: 'Suave',
    disponibilidad: 10,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a5f3855b708d4b42f816'),
    id: 16,
    nombre: 'Cocido Boyacense',
    descripcion: 'Sopa con carne, papa, yuca y plátano, típico de Boyacá.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Carne, papa, yuca, plátano',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a5f3855b708d4b42f829'),
    id: 35,
    nombre: 'Caldo de Mondongo',
    descripcion: 'Sopa espesa con mondongo (callos) y papas.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 500,
    ingredientesPrincipales: 'Mondongo, papas, especias',
    nivelPicante: 'Medio',
    disponibilidad: 15,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a5f3855b708d4b42f82b'),
    id: 37,
    nombre: 'Sobrebarriga en Salsa Criolla',
    descripcion: 'Carne de res cocida en salsa criolla, acompañada de arroz y papas.',
    precio: 40000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 750,
    ingredientesPrincipales: 'Res, salsa criolla, papas',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 9
  `
    },
    "5": {
        code: `
           _id: ObjectId('66f3a62a9ef646deb542f80b'),
    id: 5,
    nombre: 'Tamales',
    descripcion: 'Masa de maíz rellena de carne y verduras, cocida en hojas de plátano.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 90,
    calorias: 350,
    ingredientesPrincipales: 'Maíz, carne, verduras',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f80e'),
    id: 8,
    nombre: 'Bollos',
    descripcion: 'Masa de maíz con queso, envuelta en hojas de plátano y cocida al vapor.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 30,
    calorias: 250,
    ingredientesPrincipales: 'Maíz, queso',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f80f'),
    id: 9,
    nombre: 'Ceviche de camarones',
    descripcion: 'Camarones marinados en limón y acompañados de aguacate.',
    precio: 35000,
    categoria: 'Entradas',
    tiempoPreparacion: 20,
    calorias: 200,
    ingredientesPrincipales: 'Camarones, limón, aguacate',
    nivelPicante: 'Medio',
    disponibilidad: 25,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f811'),
    id: 11,
    nombre: 'Arepa de Huevo',
    descripcion: 'Arepa frita rellena de huevo, típica de la costa caribe.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 15,
    calorias: 350,
    ingredientesPrincipales: 'Maíz, huevo',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f814'),
    id: 14,
    nombre: 'Frijoles con Arracacha',
    descripcion: 'Frijoles cocidos con arracacha, acompañados de arroz.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 40,
    calorias: 350,
    ingredientesPrincipales: 'Frijoles, arracacha',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f815'),
    id: 15,
    nombre: 'Arroz con Pollo',
    descripcion: 'Arroz cocido con pollo y verduras, sazonado al gusto.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 450,
    ingredientesPrincipales: 'Arroz, pollo, verduras',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f816'),
    id: 16,
    nombre: 'Cocido Boyacense',
    descripcion: 'Sopa con carne, papa, yuca y plátano, típico de Boyacá.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Carne, papa, yuca, plátano',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f817'),
    id: 17,
    nombre: 'Pudín de pan',
    descripcion: 'Postre elaborado con pan, leche y huevo, al horno.',
    precio: 12000,
    categoria: 'Postres',
    tiempoPreparacion: 40,
    calorias: 300,
    ingredientesPrincipales: 'Pan, leche, huevo',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f818'),
    id: 18,
    nombre: 'Galletas de Arequipe',
    descripcion: 'Galletas rellenas de arequipe, un dulce tradicional.',
    precio: 5000,
    categoria: 'Postres',
    tiempoPreparacion: 15,
    calorias: 200,
    ingredientesPrincipales: 'Harina, arequipe',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f819'),
    id: 19,
    nombre: 'Morcilla',
    descripcion: 'Embutido a base de sangre, arroz y especias.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 30,
    calorias: 250,
    ingredientesPrincipales: 'Sangre, arroz',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 5
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f81a'),
    id: 20,
    nombre: 'Tamal Tolimense',
    descripcion: 'Tamales de masa de maíz con carne, vegetales y especias.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 90,
    calorias: 400,
    ingredientesPrincipales: 'Maíz, carne, vegetales',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f81b'),
    id: 21,
    nombre: 'Cocada',
    descripcion: 'Dulce de coco rallado y azúcar, típico de la región Caribe.',
    precio: 4000,
    categoria: 'Postres',
    tiempoPreparacion: 20,
    calorias: 150,
    ingredientesPrincipales: 'Coco, azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f81d'),
    id: 23,
    nombre: 'Aperitivo de Cuca',
    descripcion: 'Sándwich de cuca, un bocadillo típico de la región.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 10,
    calorias: 180,
    ingredientesPrincipales: 'Pan, carne',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f820'),
    id: 26,
    nombre: 'Aguapanela con queso',
    descripcion: 'Bebida caliente de panela, servida con queso.',
    precio: 6000,
    categoria: 'Bebidas',
    tiempoPreparacion: 5,
    calorias: 150,
    ingredientesPrincipales: 'Panela, agua, queso',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f821'),
    id: 27,
    nombre: 'Mazamorra',
    descripcion: 'Postre de maíz con leche, típico del interior de Colombia.',
    precio: 5000,
    categoria: 'Postres',
    tiempoPreparacion: 10,
    calorias: 250,
    ingredientesPrincipales: 'Maíz, leche, azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f823'),
    id: 29,
    nombre: 'Tamal Santafereño',
    descripcion: 'Tamales elaborados con masa de maíz y varios rellenos, típicos de Bogotá.',
    precio: 18000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Maíz, carne, vegetales',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f824'),
    id: 30,
    nombre: 'Sudado de Pollo',
    descripcion: 'Pollo cocido en salsa con papas y yuca, acompañado de arroz.',
    precio: 25000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 40,
    calorias: 600,
    ingredientesPrincipales: 'Pollo, papas, yuca',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f825'),
    id: 31,
    nombre: 'Chontaduro con sal y miel',
    descripcion: 'Fruta tropical, servida con sal y miel.',
    precio: 10000,
    categoria: 'Postres',
    tiempoPreparacion: 5,
    calorias: 150,
    ingredientesPrincipales: 'Chontaduro, sal, miel',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f826'),
    id: 32,
    nombre: 'Arroz con Leche',
    descripcion: 'Postre cremoso de arroz cocido en leche con canela.',
    precio: 8000,
    categoria: 'Postres',
    tiempoPreparacion: 30,
    calorias: 300,
    ingredientesPrincipales: 'Arroz, leche, canela',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a62a9ef646deb542f829'),
    id: 35,
    nombre: 'Caldo de Mondongo',
    descripcion: 'Sopa espesa con mondongo (callos) y papas.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 500,
    ingredientesPrincipales: 'Mondongo, papas, especias',
    nivelPicante: 'Medio',
    disponibilidad: 15,
    popularidad: 7
  `
    },
    "6": {
        code: `
           _id: ObjectId('66f3a65357bbadffad42f80f'),
    id: 9,
    nombre: 'Ceviche de camarones',
    descripcion: 'Camarones marinados en limón y acompañados de aguacate.',
    precio: 35000,
    categoria: 'Entradas',
    tiempoPreparacion: 20,
    calorias: 200,
    ingredientesPrincipales: 'Camarones, limón, aguacate',
    nivelPicante: 'Medio',
    disponibilidad: 25,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a65357bbadffad42f829'),
    id: 35,
    nombre: 'Caldo de Mondongo',
    descripcion: 'Sopa espesa con mondongo (callos) y papas.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 500,
    ingredientesPrincipales: 'Mondongo, papas, especias',
    nivelPicante: 'Medio',
    disponibilidad: 15,
    popularidad: 7
  `
    },
    "7": {
        code: `
          _id: ObjectId('66f3a688bc0cff1b1c42f807'),
    id: 1,
    nombre: 'Arepas',
    descripcion: 'Tortillas de maíz, rellenas de queso, carne o huevo.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 15,
    calorias: 200,
    ingredientesPrincipales: 'Maíz, queso, carne',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f809'),
    id: 3,
    nombre: 'Ajiaco',
    descripcion: 'Sopa de pollo con papas y maíz, servida con crema y aguacate.',
    precio: 35000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 400,
    ingredientesPrincipales: 'Pollo, papas, maíz, crema, aguacate',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f80c'),
    id: 6,
    nombre: 'Empanadas',
    descripcion: 'Masa rellena de carne, pollo o queso, fritas o al horno.',
    precio: 10000,
    categoria: 'Entradas',
    tiempoPreparacion: 20,
    calorias: 300,
    ingredientesPrincipales: 'Masa, carne, pollo, queso',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f80f'),
    id: 9,
    nombre: 'Ceviche de camarones',
    descripcion: 'Camarones marinados en limón y acompañados de aguacate.',
    precio: 35000,
    categoria: 'Entradas',
    tiempoPreparacion: 20,
    calorias: 200,
    ingredientesPrincipales: 'Camarones, limón, aguacate',
    nivelPicante: 'Medio',
    disponibilidad: 25,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f813'),
    id: 13,
    nombre: 'Patacones',
    descripcion: 'Plátanos verdes fritos, crujientes y servidos con guacamole.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 20,
    calorias: 400,
    ingredientesPrincipales: 'Plátano verde, aceite',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f817'),
    id: 17,
    nombre: 'Pudín de pan',
    descripcion: 'Postre elaborado con pan, leche y huevo, al horno.',
    precio: 12000,
    categoria: 'Postres',
    tiempoPreparacion: 40,
    calorias: 300,
    ingredientesPrincipales: 'Pan, leche, huevo',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f818'),
    id: 18,
    nombre: 'Galletas de Arequipe',
    descripcion: 'Galletas rellenas de arequipe, un dulce tradicional.',
    precio: 5000,
    categoria: 'Postres',
    tiempoPreparacion: 15,
    calorias: 200,
    ingredientesPrincipales: 'Harina, arequipe',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f81a'),
    id: 20,
    nombre: 'Tamal Tolimense',
    descripcion: 'Tamales de masa de maíz con carne, vegetales y especias.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 90,
    calorias: 400,
    ingredientesPrincipales: 'Maíz, carne, vegetales',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f826'),
    id: 32,
    nombre: 'Arroz con Leche',
    descripcion: 'Postre cremoso de arroz cocido en leche con canela.',
    precio: 8000,
    categoria: 'Postres',
    tiempoPreparacion: 30,
    calorias: 300,
    ingredientesPrincipales: 'Arroz, leche, canela',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f827'),
    id: 33,
    nombre: 'Carimañolas',
    descripcion: 'Masa de yuca rellena de carne o queso, frita hasta quedar crujiente.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 20,
    calorias: 400,
    ingredientesPrincipales: 'Yuca, carne, queso',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f82c'),
    id: 38,
    nombre: 'Yuca Frita',
    descripcion: 'Yuca frita crujiente, servida con salsa de su preferencia.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 15,
    calorias: 400,
    ingredientesPrincipales: 'Yuca, aceite',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a688bc0cff1b1c42f82e'),
    id: 40,
    nombre: 'Aguardiente',
    descripcion: 'Bebida alcohólica tradicional de Colombia, hecha de caña de azúcar.',
    precio: 20000,
    categoria: 'Bebidas',
    tiempoPreparacion: 0,
    calorias: 200,
    ingredientesPrincipales: 'Caña de azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 100,
    popularidad: 10
  `
    },
    "8": {
        code: `
         _id: ObjectId('66f3a6cb380781efe242f808'),
    id: 2,
    nombre: 'Bandeja Paisa',
    descripcion: 'Plato tradicional con frijoles, arroz, carne, chicharrón y aguacate.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 800,
    ingredientesPrincipales: 'Frijoles, arroz, carne, chicharrón, aguacate',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f80a'),
    id: 4,
    nombre: 'Sancocho',
    descripcion: 'Sopa de carne con yuca, plátano y maíz.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Carne, yuca, plátano, maíz',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f80b'),
    id: 5,
    nombre: 'Tamales',
    descripcion: 'Masa de maíz rellena de carne y verduras, cocida en hojas de plátano.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 90,
    calorias: 350,
    ingredientesPrincipales: 'Maíz, carne, verduras',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f80d'),
    id: 7,
    nombre: 'Posta Negra Cartagenera',
    descripcion: 'Carne de res en salsa negra, acompañada de arroz y plátano.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 50,
    calorias: 600,
    ingredientesPrincipales: 'Carne de res, salsa negra',
    nivelPicante: 'Suave',
    disponibilidad: 10,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f80e'),
    id: 8,
    nombre: 'Bollos',
    descripcion: 'Masa de maíz con queso, envuelta en hojas de plátano y cocida al vapor.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 30,
    calorias: 250,
    ingredientesPrincipales: 'Maíz, queso',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f810'),
    id: 10,
    nombre: 'Pargo frito',
    descripcion: 'Pescado frito, servido con arroz y ensalada.',
    precio: 45000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 500,
    ingredientesPrincipales: 'Pargo, arroz, ensalada',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f811'),
    id: 11,
    nombre: 'Arepa de Huevo',
    descripcion: 'Arepa frita rellena de huevo, típica de la costa caribe.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 15,
    calorias: 350,
    ingredientesPrincipales: 'Maíz, huevo',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f812'),
    id: 12,
    nombre: 'Lechona',
    descripcion: 'Cerdo asado relleno de arroz, guisantes y especias.',
    precio: 60000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 120,
    calorias: 800,
    ingredientesPrincipales: 'Cerdo, arroz, guisantes',
    nivelPicante: 'Suave',
    disponibilidad: 10,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f814'),
    id: 14,
    nombre: 'Frijoles con Arracacha',
    descripcion: 'Frijoles cocidos con arracacha, acompañados de arroz.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 40,
    calorias: 350,
    ingredientesPrincipales: 'Frijoles, arracacha',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f815'),
    id: 15,
    nombre: 'Arroz con Pollo',
    descripcion: 'Arroz cocido con pollo y verduras, sazonado al gusto.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 450,
    ingredientesPrincipales: 'Arroz, pollo, verduras',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f816'),
    id: 16,
    nombre: 'Cocido Boyacense',
    descripcion: 'Sopa con carne, papa, yuca y plátano, típico de Boyacá.',
    precio: 30000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 500,
    ingredientesPrincipales: 'Carne, papa, yuca, plátano',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f819'),
    id: 19,
    nombre: 'Morcilla',
    descripcion: 'Embutido a base de sangre, arroz y especias.',
    precio: 12000,
    categoria: 'Entradas',
    tiempoPreparacion: 30,
    calorias: 250,
    ingredientesPrincipales: 'Sangre, arroz',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 5
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f81b'),
    id: 21,
    nombre: 'Cocada',
    descripcion: 'Dulce de coco rallado y azúcar, típico de la región Caribe.',
    precio: 4000,
    categoria: 'Postres',
    tiempoPreparacion: 20,
    calorias: 150,
    ingredientesPrincipales: 'Coco, azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f81c'),
    id: 22,
    nombre: 'Buñuelos',
    descripcion: 'Dulces fritos de masa de queso, servidos calientes.',
    precio: 15000,
    categoria: 'Postres',
    tiempoPreparacion: 25,
    calorias: 250,
    ingredientesPrincipales: 'Queso, harina',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f81d'),
    id: 23,
    nombre: 'Aperitivo de Cuca',
    descripcion: 'Sándwich de cuca, un bocadillo típico de la región.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 10,
    calorias: 180,
    ingredientesPrincipales: 'Pan, carne',
    nivelPicante: 'Suave',
    disponibilidad: 30,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f81e'),
    id: 24,
    nombre: 'Chicha',
    descripcion: 'Bebida fermentada a base de maíz, tradicional en Colombia.',
    precio: 5000,
    categoria: 'Bebidas',
    tiempoPreparacion: 0,
    calorias: 100,
    ingredientesPrincipales: 'Maíz',
    nivelPicante: 'Suave',
    disponibilidad: 60,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f81f'),
    id: 25,
    nombre: 'Jugo de Lulo',
    descripcion: 'Jugo refrescante hecho de lulo, una fruta típica.',
    precio: 12000,
    categoria: 'Bebidas',
    tiempoPreparacion: 5,
    calorias: 80,
    ingredientesPrincipales: 'Lulo, agua, azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f820'),
    id: 26,
    nombre: 'Aguapanela con queso',
    descripcion: 'Bebida caliente de panela, servida con queso.',
    precio: 6000,
    categoria: 'Bebidas',
    tiempoPreparacion: 5,
    calorias: 150,
    ingredientesPrincipales: 'Panela, agua, queso',
    nivelPicante: 'Suave',
    disponibilidad: 50,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f821'),
    id: 27,
    nombre: 'Mazamorra',
    descripcion: 'Postre de maíz con leche, típico del interior de Colombia.',
    precio: 5000,
    categoria: 'Postres',
    tiempoPreparacion: 10,
    calorias: 250,
    ingredientesPrincipales: 'Maíz, leche, azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a6cb380781efe242f822'),
    id: 28,
    nombre: 'Caldo de Costilla',
    descripcion: 'Sopa caliente de costilla de res con papas y especias.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 30,
    calorias: 350,
    ingredientesPrincipales: 'Costilla de res, papa, especias',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 8
  
  `
    },
    "9": {
        code: `
         _id: ObjectId('66f3a6f570d461277242f817'),
    id: 17,
    nombre: 'Pudín de pan',
    descripcion: 'Postre elaborado con pan, leche y huevo, al horno.',
    precio: 12000,
    categoria: 'Postres',
    tiempoPreparacion: 40,
    calorias: 300,
    ingredientesPrincipales: 'Pan, leche, huevo',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a6f570d461277242f81c'),
    id: 22,
    nombre: 'Buñuelos',
    descripcion: 'Dulces fritos de masa de queso, servidos calientes.',
    precio: 15000,
    categoria: 'Postres',
    tiempoPreparacion: 25,
    calorias: 250,
    ingredientesPrincipales: 'Queso, harina',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a6f570d461277242f821'),
    id: 27,
    nombre: 'Mazamorra',
    descripcion: 'Postre de maíz con leche, típico del interior de Colombia.',
    precio: 5000,
    categoria: 'Postres',
    tiempoPreparacion: 10,
    calorias: 250,
    ingredientesPrincipales: 'Maíz, leche, azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a6f570d461277242f826'),
    id: 32,
    nombre: 'Arroz con Leche',
    descripcion: 'Postre cremoso de arroz cocido en leche con canela.',
    precio: 8000,
    categoria: 'Postres',
    tiempoPreparacion: 30,
    calorias: 300,
    ingredientesPrincipales: 'Arroz, leche, canela',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 7
  `
    },
    "10": {
        code: `
          precio original:
          precio: 12000
        ---------------------------------------------------------
        ---------------------------------------------------------
        ---------------------------------------------------------
      _id: ObjectId('66f3a72515722b2f4e42f825'),
    id: 31,
    nombre: 'Chontaduro con sal y miel',
    descripcion: 'Fruta tropical, servida con sal y miel.',
    precio: 10000,
    categoria: 'Postres',
    tiempoPreparacion: 5,
    calorias: 150,
    ingredientesPrincipales: 'Chontaduro, sal, miel',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 6
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f826'),
    id: 32,
    nombre: 'Arroz con Leche',
    descripcion: 'Postre cremoso de arroz cocido en leche con canela.',
    precio: 8000,
    categoria: 'Postres',
    tiempoPreparacion: 30,
    calorias: 300,
    ingredientesPrincipales: 'Arroz, leche, canela',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f827'),
    id: 33,
    nombre: 'Carimañolas',
    descripcion: 'Masa de yuca rellena de carne o queso, frita hasta quedar crujiente.',
    precio: 15000,
    categoria: 'Entradas',
    tiempoPreparacion: 20,
    calorias: 400,
    ingredientesPrincipales: 'Yuca, carne, queso',
    nivelPicante: 'Suave',
    disponibilidad: 25,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f828'),
    id: 34,
    nombre: 'Arroz Atollado',
    descripcion: 'Arroz cremoso con cerdo, chorizo y papas, típico del Valle del Cauca.',
    precio: 35000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 50,
    calorias: 700,
    ingredientesPrincipales: 'Arroz, cerdo, chorizo, papas',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f829'),
    id: 35,
    nombre: 'Caldo de Mondongo',
    descripcion: 'Sopa espesa con mondongo (callos) y papas.',
    precio: 20000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 45,
    calorias: 500,
    ingredientesPrincipales: 'Mondongo, papas, especias',
    nivelPicante: 'Medio',
    disponibilidad: 15,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f82a'),
    id: 36,
    nombre: 'Chuleta Valluna',
    descripcion: 'Carne de cerdo empanizada y frita, servida con arroz y ensalada.',
    precio: 35000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 40,
    calorias: 700,
    ingredientesPrincipales: 'Cerdo, harina, ensalada',
    nivelPicante: 'Suave',
    disponibilidad: 20,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f82b'),
    id: 37,
    nombre: 'Sobrebarriga en Salsa Criolla',
    descripcion: 'Carne de res cocida en salsa criolla, acompañada de arroz y papas.',
    precio: 40000,
    categoria: 'Platos Principales',
    tiempoPreparacion: 60,
    calorias: 750,
    ingredientesPrincipales: 'Res, salsa criolla, papas',
    nivelPicante: 'Suave',
    disponibilidad: 15,
    popularidad: 9
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f82c'),
    id: 38,
    nombre: 'Yuca Frita',
    descripcion: 'Yuca frita crujiente, servida con salsa de su preferencia.',
    precio: 20000,
    categoria: 'Entradas',
    tiempoPreparacion: 15,
    calorias: 400,
    ingredientesPrincipales: 'Yuca, aceite',
    nivelPicante: 'Suave',
    disponibilidad: 35,
    popularidad: 7
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f82d'),
    id: 39,
    nombre: 'Hogao',
    descripcion: 'Salsa a base de cebolla y tomate, utilizada como acompañamiento.',
    precio: 8000,
    categoria: 'Entradas',
    tiempoPreparacion: 20,
    calorias: 150,
    ingredientesPrincipales: 'Cebolla, tomate, ajo',
    nivelPicante: 'Suave',
    disponibilidad: 40,
    popularidad: 8
  },
  {
    _id: ObjectId('66f3a72515722b2f4e42f82e'),
    id: 40,
    nombre: 'Aguardiente',
    descripcion: 'Bebida alcohólica tradicional de Colombia, hecha de caña de azúcar.',
    precio: 20000,
    categoria: 'Bebidas',
    tiempoPreparacion: 0,
    calorias: 200,
    ingredientesPrincipales: 'Caña de azúcar',
    nivelPicante: 'Suave',
    disponibilidad: 100,
    popularidad: 10    

  `
    },
};


// Modal
const modal = document.getElementById("modal");
const modalCode = document.getElementById("modal-code");
const closeModal = document.querySelector(".close");

// Función para abrir el modal
document.querySelectorAll('.view-more-btn').forEach(button => {
    button.addEventListener('click', (e) => {
        const cardId = e.target.getAttribute('data-card');
        
        // Configurar código según la tarjeta
        if (cardId && cardCodeDetails[cardId]) {
            modalCode.textContent = cardCodeDetails[cardId].code;
        }
        
        modal.style.display = "block";
    });
});

// Cerrar modal
closeModal.addEventListener('click', () => {
    modal.style.display = "none";
});
