// Detalles de los códigos para cada tarjeta
const cardCodeDetails = {
    "1": {
        code: `
          _id: ObjectId('66f39d55a78e7e675842f809'),
    id: 3,
    nombre: 'Algoritmos y Programacion 1',
    CodigoMateria: 84003,
    Descripcion: 'Introducción a la lógica de programación y desarrollo de algoritmos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 601,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
`
    },
    "2": {
        code: `
          _id: ObjectId('66f39e67ee1a3d933d42f809'),
    id: 3,
    nombre: 'Algoritmos y Programacion 1',
    CodigoMateria: 84003,
    Descripcion: 'Introducción a la lógica de programación y desarrollo de algoritmos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 601,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f80d'),
    id: 7,
    nombre: 'Algoritmos y Programacion 2',
    CodigoMateria: 84012,
    Descripcion: 'Profundización en algoritmos y estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f80e'),
    id: 8,
    nombre: 'Mecanica',
    CodigoMateria: 84013,
    Descripcion: 'Estudio de los principios básicos de la mecánica clásica.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 604,
    Prerrequisitos: 'Introduccion a la ingenieria',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f814'),
    id: 14,
    nombre: 'Algoritmos y Programacion 3',
    CodigoMateria: 84021,
    Descripcion: 'Avance en la implementación de algoritmos y manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 2 y Algoritmos y Programacion 1',
    PromedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f818'),
    id: 18,
    nombre: 'Maquinas Electricas',
    CodigoMateria: 84027,
    Descripcion: 'Estudio de máquinas eléctricas y sus aplicaciones en la ingeniería.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 603,
    Prerrequisitos: 'Electricidad y Magnetismo',
    PromedioCalificaciones: 4.9
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f819'),
    id: 19,
    nombre: 'Estructura De Datos 1',
    CodigoMateria: 84028,
    Descripcion: 'Análisis y diseño de estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1, 2 y 3',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f81a'),
    id: 20,
    nombre: 'Interaccion Hombre Maquina',
    CodigoMateria: 84029,
    Descripcion: 'Diseño y evaluación de interfaces entre personas y sistemas computacionales.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 603,
    Prerrequisitos: 'Algoritmos y Programacion 1 y Matematicas Discretas',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f81b'),
    id: 21,
    nombre: 'Probabilidad y Estadistica Descriptiva',
    CodigoMateria: 84030,
    Descripcion: 'Fundamentos de probabilidad y análisis de datos estadísticos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 602,
    Prerrequisitos: 'Metodos Numericos',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f81c'),
    id: 22,
    nombre: 'Teoria de Bases de datos',
    CodigoMateria: 84033,
    Descripcion: 'Estudio de los principios fundamentales de las bases de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Danny Michael Cardenas Martínez',
    Aula: 604,
    Prerrequisitos: 'Interaccion Hombre Maquina',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f81d'),
    id: 23,
    nombre: 'Estructura de datos 2',
    CodigoMateria: 84034,
    Descripcion: 'Profundización en el manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Estructura de Datos 1',
    PromedioCalificaciones: 4.1
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f81e'),
    id: 24,
    nombre: 'Estadistica Inferencial',
    CodigoMateria: 84035,
    Descripcion: 'Análisis y validación de datos estadísticos mediante técnicas inferenciales.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 105,
    Prerrequisitos: 'Probabilidad y Estadistica Descriptiva',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f81f'),
    id: 25,
    nombre: 'Electronica Digital',
    CodigoMateria: 84036,
    Descripcion: 'Introducción a los principios de redes de computadoras y su funcionamiento.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 603,
    Prerrequisitos: 'Interaccion Hombre Maquina y Teoria de Bases de datos',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f821'),
    id: 27,
    nombre: 'Formulacion y Gestion de proyectos',
    CodigoMateria: 84038,
    Descripcion: 'Principios y prácticas de seguridad informática.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Wilsón Andrés Castillo Castro',
    Aula: 605,
    Prerrequisitos: 'Redes de Computadores 1',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f822'),
    id: 28,
    nombre: 'Practica de bases de datos',
    CodigoMateria: 84041,
    Descripcion: 'Estudio de los fundamentos y arquitectura de los sistemas operativos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 603,
    Prerrequisitos: 'Algoritmos y Programacion 2',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f823'),
    id: 29,
    nombre: 'Analisis y Modelamiento de Software',
    CodigoMateria: 84042,
    Descripcion: 'Estudio de la estructura interna y funcionamiento de los computadores.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Giovanni Albeiro Hernández Pantoja',
    Aula: 601,
    Prerrequisitos: 'Sistemas Operativos',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f824'),
    id: 30,
    nombre: 'Arquitectura de Computadores',
    CodigoMateria: 84043,
    Descripcion: 'Uso de modelos matemáticos para la simulación de sistemas complejos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 604,
    Prerrequisitos: 'Metodos Numericos',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f825'),
    id: 31,
    nombre: 'Sistemas Operativos',
    CodigoMateria: 84044,
    Descripcion: 'Principios, métodos y herramientas para la ingeniería de software.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Wilsón Andrés Castillo Castro',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 3',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f826'),
    id: 32,
    nombre: 'Simulacion',
    CodigoMateria: 84045,
    Descripcion: 'Fundamentos y técnicas para el desarrollo de aplicaciones web.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Danny Michael Cardenas Martínez',
    Aula: 603,
    Prerrequisitos: 'Interaccion Hombre Maquina',
    PromedioCalificaciones: 4.6
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f829'),
    id: 35,
    nombre: 'Construccion de sistemas de informacion',
    CodigoMateria: 84050,
    Descripcion: 'Estudio de las bases de datos distribuidas y su implementación.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 603,
    Prerrequisitos: 'Teoria de Bases de datos',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e67ee1a3d933d42f82a'),
    id: 36,
    nombre: 'Ingenieria de Software',
    CodigoMateria: 84051,
    Descripcion: 'Introducción a los principios y aplicaciones de la robótica.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Giovanni Albeiro Hernández Pantoja',
    Aula: 604,
    Prerrequisitos: 'Algoritmos y Programacion 3',
    PromedioCalificaciones: 4.7
`
    },
    "3": {
        code: `
           _id: ObjectId('66f39e985b8bfed9f842f807'),
    id: 1,
    nombre: 'Fundamento Matematico',
    CodigoMateria: 84001,
    Descripcion: 'Estudio de los conceptos básicos y fundamentales de las matemáticas.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 206,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f808'),
    id: 2,
    nombre: 'Logica Matematica',
    CodigoMateria: 84002,
    Descripcion: 'Desarrollo del pensamiento lógico y matemático a través de estructuras formales.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 307,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f809'),
    id: 3,
    nombre: 'Algoritmos y Programacion 1',
    CodigoMateria: 84003,
    Descripcion: 'Introducción a la lógica de programación y desarrollo de algoritmos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 601,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f80b'),
    id: 5,
    nombre: 'Algebra Lineal',
    CodigoMateria: 84010,
    Descripcion: 'Estudio de vectores, matrices y espacios vectoriales.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 105,
    Prerrequisitos: 'Logica Matematica',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f80c'),
    id: 6,
    nombre: 'Calculo Diferencial',
    CodigoMateria: 84011,
    Descripcion: 'Fundamentos del cálculo diferencial y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 603,
    Prerrequisitos: 'Logica Matematica, Fundamento Matematico',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f80d'),
    id: 7,
    nombre: 'Algoritmos y Programacion 2',
    CodigoMateria: 84012,
    Descripcion: 'Profundización en algoritmos y estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f80e'),
    id: 8,
    nombre: 'Mecanica',
    CodigoMateria: 84013,
    Descripcion: 'Estudio de los principios básicos de la mecánica clásica.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 604,
    Prerrequisitos: 'Introduccion a la ingenieria',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f810'),
    id: 10,
    nombre: 'Humanismo Cristiano',
    CodigoMateria: 84015,
    Descripcion: 'Estudio de los valores y principios del humanismo cristiano.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 603,
    Prerrequisitos: 'Pensamiento Filosofico',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f811'),
    id: 11,
    nombre: 'Matematicas Discretas',
    CodigoMateria: 84018,
    Descripcion: 'Estudio de estructuras matemáticas discretas como conjuntos y grafos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 106,
    Prerrequisitos: 'Algebra Lineal',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f812'),
    id: 12,
    nombre: 'Calculo Integral',
    CodigoMateria: 84019,
    Descripcion: 'Fundamentos del cálculo integral y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 602,
    Prerrequisitos: 'Calculo Diferencial',
    PromedioCalificaciones: 3.9
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f813'),
    id: 13,
    nombre: 'Metodos Numericos',
    CodigoMateria: 84020,
    Descripcion: 'Estudio de métodos numéricos para la solución de problemas matemáticos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 304,
    Prerrequisitos: 'Algebra Lineal',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f814'),
    id: 14,
    nombre: 'Algoritmos y Programacion 3',
    CodigoMateria: 84021,
    Descripcion: 'Avance en la implementación de algoritmos y manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 2 y Algoritmos y Programacion 1',
    PromedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f815'),
    id: 15,
    nombre: 'Electricidad y Magnetismo',
    CodigoMateria: 84022,
    Descripcion: 'Estudio de los fenómenos eléctricos y magnéticos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 603,
    Prerrequisitos: 'Mecanica',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f816'),
    id: 16,
    nombre: 'Etica Profesional',
    CodigoMateria: 84023,
    Descripcion: 'Reflexión sobre la ética en el ejercicio profesional.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 604,
    Prerrequisitos: 'Humanismo Cristiano',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f817'),
    id: 17,
    nombre: 'Ecuaciones Diferenciales',
    CodigoMateria: 84026,
    Descripcion: 'Solución de ecuaciones diferenciales y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 105,
    Prerrequisitos: 'Calculo Diferencial y Calculo Integral',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f818'),
    id: 18,
    nombre: 'Maquinas Electricas',
    CodigoMateria: 84027,
    Descripcion: 'Estudio de máquinas eléctricas y sus aplicaciones en la ingeniería.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 603,
    Prerrequisitos: 'Electricidad y Magnetismo',
    PromedioCalificaciones: 4.9
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f819'),
    id: 19,
    nombre: 'Estructura De Datos 1',
    CodigoMateria: 84028,
    Descripcion: 'Análisis y diseño de estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1, 2 y 3',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f81a'),
    id: 20,
    nombre: 'Interaccion Hombre Maquina',
    CodigoMateria: 84029,
    Descripcion: 'Diseño y evaluación de interfaces entre personas y sistemas computacionales.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 603,
    Prerrequisitos: 'Algoritmos y Programacion 1 y Matematicas Discretas',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f81b'),
    id: 21,
    nombre: 'Probabilidad y Estadistica Descriptiva',
    CodigoMateria: 84030,
    Descripcion: 'Fundamentos de probabilidad y análisis de datos estadísticos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 602,
    Prerrequisitos: 'Metodos Numericos',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39e985b8bfed9f842f81c'),
    id: 22,
    nombre: 'Teoria de Bases de datos',
    CodigoMateria: 84033,
    Descripcion: 'Estudio de los principios fundamentales de las bases de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Danny Michael Cardenas Martínez',
    Aula: 604,
    Prerrequisitos: 'Interaccion Hombre Maquina',
    PromedioCalificaciones: 4.4
`
    },
    "4": {
        code: `
          _id: ObjectId('66f39ecf72ade3a64042f80a'),
    id: 4,
    nombre: 'Lectoescritura Investigativa',
    CodigoMateria: 84005,
    Descripcion: 'Desarrollo de habilidades de lectura crítica y escritura científica.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 308,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39ecf72ade3a64042f80f'),
    id: 9,
    nombre: 'Epistemologia Especifica',
    CodigoMateria: 84014,
    Descripcion: 'Reflexión crítica sobre el conocimiento en un campo particular.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 304,
    Prerrequisitos: 'Lectoescritura Investigativa',
    PromedioCalificaciones: 4.6
  `
    },
    "5": {
        code: `
           _id: ObjectId('66f39ef629ff23f17742f807'),
    id: 1,
    nombre: 'Fundamento Matematico',
    CodigoMateria: 84001,
    Descripcion: 'Estudio de los conceptos básicos y fundamentales de las matemáticas.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 206,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f808'),
    id: 2,
    nombre: 'Logica Matematica',
    CodigoMateria: 84002,
    Descripcion: 'Desarrollo del pensamiento lógico y matemático a través de estructuras formales.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 307,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f809'),
    id: 3,
    nombre: 'Algoritmos y Programacion 1',
    CodigoMateria: 84003,
    Descripcion: 'Introducción a la lógica de programación y desarrollo de algoritmos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 601,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f80a'),
    id: 4,
    nombre: 'Lectoescritura Investigativa',
    CodigoMateria: 84005,
    Descripcion: 'Desarrollo de habilidades de lectura crítica y escritura científica.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 308,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f80b'),
    id: 5,
    nombre: 'Algebra Lineal',
    CodigoMateria: 84010,
    Descripcion: 'Estudio de vectores, matrices y espacios vectoriales.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 105,
    Prerrequisitos: 'Logica Matematica',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f80c'),
    id: 6,
    nombre: 'Calculo Diferencial',
    CodigoMateria: 84011,
    Descripcion: 'Fundamentos del cálculo diferencial y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 603,
    Prerrequisitos: 'Logica Matematica, Fundamento Matematico',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f80d'),
    id: 7,
    nombre: 'Algoritmos y Programacion 2',
    CodigoMateria: 84012,
    Descripcion: 'Profundización en algoritmos y estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f80e'),
    id: 8,
    nombre: 'Mecanica',
    CodigoMateria: 84013,
    Descripcion: 'Estudio de los principios básicos de la mecánica clásica.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 604,
    Prerrequisitos: 'Introduccion a la ingenieria',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f80f'),
    id: 9,
    nombre: 'Epistemologia Especifica',
    CodigoMateria: 84014,
    Descripcion: 'Reflexión crítica sobre el conocimiento en un campo particular.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 304,
    Prerrequisitos: 'Lectoescritura Investigativa',
    PromedioCalificaciones: 4.6
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f810'),
    id: 10,
    nombre: 'Humanismo Cristiano',
    CodigoMateria: 84015,
    Descripcion: 'Estudio de los valores y principios del humanismo cristiano.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 603,
    Prerrequisitos: 'Pensamiento Filosofico',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f811'),
    id: 11,
    nombre: 'Matematicas Discretas',
    CodigoMateria: 84018,
    Descripcion: 'Estudio de estructuras matemáticas discretas como conjuntos y grafos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 106,
    Prerrequisitos: 'Algebra Lineal',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f812'),
    id: 12,
    nombre: 'Calculo Integral',
    CodigoMateria: 84019,
    Descripcion: 'Fundamentos del cálculo integral y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 602,
    Prerrequisitos: 'Calculo Diferencial',
    PromedioCalificaciones: 3.9
  },
  {
    _id: ObjectId('66f39ef629ff23f17742f813'),
    id: 13,
    nombre: 'Metodos Numericos',
    CodigoMateria: 84020,
    Descripcion: 'Estudio de métodos numéricos para la solución de problemas matemáticos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 304,
    Prerrequisitos: 'Algebra Lineal',
    PromedioCalificaciones: 4.5
  `
    },
    "6": {
        code: `
          _id: ObjectId('66f39f463f6f840d1f42f809'),
    id: 3,
    nombre: 'Algoritmos y Programacion 1',
    CodigoMateria: 84003,
    Descripcion: 'Introducción a la lógica de programación y desarrollo de algoritmos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 601,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f80a'),
    id: 4,
    nombre: 'Lectoescritura Investigativa',
    CodigoMateria: 84005,
    Descripcion: 'Desarrollo de habilidades de lectura crítica y escritura científica.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 308,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f80b'),
    id: 5,
    nombre: 'Algebra Lineal',
    CodigoMateria: 84010,
    Descripcion: 'Estudio de vectores, matrices y espacios vectoriales.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 105,
    Prerrequisitos: 'Logica Matematica',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f80c'),
    id: 6,
    nombre: 'Calculo Diferencial',
    CodigoMateria: 84011,
    Descripcion: 'Fundamentos del cálculo diferencial y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 603,
    Prerrequisitos: 'Logica Matematica, Fundamento Matematico',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f80d'),
    id: 7,
    nombre: 'Algoritmos y Programacion 2',
    CodigoMateria: 84012,
    Descripcion: 'Profundización en algoritmos y estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f80e'),
    id: 8,
    nombre: 'Mecanica',
    CodigoMateria: 84013,
    Descripcion: 'Estudio de los principios básicos de la mecánica clásica.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 604,
    Prerrequisitos: 'Introduccion a la ingenieria',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f80f'),
    id: 9,
    nombre: 'Epistemologia Especifica',
    CodigoMateria: 84014,
    Descripcion: 'Reflexión crítica sobre el conocimiento en un campo particular.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 304,
    Prerrequisitos: 'Lectoescritura Investigativa',
    PromedioCalificaciones: 4.6
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f810'),
    id: 10,
    nombre: 'Humanismo Cristiano',
    CodigoMateria: 84015,
    Descripcion: 'Estudio de los valores y principios del humanismo cristiano.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 603,
    Prerrequisitos: 'Pensamiento Filosofico',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f811'),
    id: 11,
    nombre: 'Matematicas Discretas',
    CodigoMateria: 84018,
    Descripcion: 'Estudio de estructuras matemáticas discretas como conjuntos y grafos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 106,
    Prerrequisitos: 'Algebra Lineal',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f812'),
    id: 12,
    nombre: 'Calculo Integral',
    CodigoMateria: 84019,
    Descripcion: 'Fundamentos del cálculo integral y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 602,
    Prerrequisitos: 'Calculo Diferencial',
    PromedioCalificaciones: 3.9
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f813'),
    id: 13,
    nombre: 'Metodos Numericos',
    CodigoMateria: 84020,
    Descripcion: 'Estudio de métodos numéricos para la solución de problemas matemáticos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 304,
    Prerrequisitos: 'Algebra Lineal',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f814'),
    id: 14,
    nombre: 'Algoritmos y Programacion 3',
    CodigoMateria: 84021,
    Descripcion: 'Avance en la implementación de algoritmos y manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 2 y Algoritmos y Programacion 1',
    PromedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f815'),
    id: 15,
    nombre: 'Electricidad y Magnetismo',
    CodigoMateria: 84022,
    Descripcion: 'Estudio de los fenómenos eléctricos y magnéticos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 603,
    Prerrequisitos: 'Mecanica',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f816'),
    id: 16,
    nombre: 'Etica Profesional',
    CodigoMateria: 84023,
    Descripcion: 'Reflexión sobre la ética en el ejercicio profesional.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 604,
    Prerrequisitos: 'Humanismo Cristiano',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f818'),
    id: 18,
    nombre: 'Maquinas Electricas',
    CodigoMateria: 84027,
    Descripcion: 'Estudio de máquinas eléctricas y sus aplicaciones en la ingeniería.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 603,
    Prerrequisitos: 'Electricidad y Magnetismo',
    PromedioCalificaciones: 4.9
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f819'),
    id: 19,
    nombre: 'Estructura De Datos 1',
    CodigoMateria: 84028,
    Descripcion: 'Análisis y diseño de estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1, 2 y 3',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f81a'),
    id: 20,
    nombre: 'Interaccion Hombre Maquina',
    CodigoMateria: 84029,
    Descripcion: 'Diseño y evaluación de interfaces entre personas y sistemas computacionales.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 603,
    Prerrequisitos: 'Algoritmos y Programacion 1 y Matematicas Discretas',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f81c'),
    id: 22,
    nombre: 'Teoria de Bases de datos',
    CodigoMateria: 84033,
    Descripcion: 'Estudio de los principios fundamentales de las bases de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Danny Michael Cardenas Martínez',
    Aula: 604,
    Prerrequisitos: 'Interaccion Hombre Maquina',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f81d'),
    id: 23,
    nombre: 'Estructura de datos 2',
    CodigoMateria: 84034,
    Descripcion: 'Profundización en el manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Estructura de Datos 1',
    PromedioCalificaciones: 4.1
  },
  {
    _id: ObjectId('66f39f463f6f840d1f42f81f'),
    id: 25,
    nombre: 'Electronica Digital',
    CodigoMateria: 84036,
    Descripcion: 'Introducción a los principios de redes de computadoras y su funcionamiento.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 603,
    Prerrequisitos: 'Interaccion Hombre Maquina y Teoria de Bases de datos',
    PromedioCalificaciones: 4.7
  `
    },
    "7": {
        code: `
          _id: ObjectId('66f39f9afa9af32f0942f80c'),
    id: 6,
    nombre: 'Calculo Diferencial',
    CodigoMateria: 84011,
    Descripcion: 'Fundamentos del cálculo diferencial y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 603,
    Prerrequisitos: 'Logica Matematica, Fundamento Matematico',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f810'),
    id: 10,
    nombre: 'Humanismo Cristiano',
    CodigoMateria: 84015,
    Descripcion: 'Estudio de los valores y principios del humanismo cristiano.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 603,
    Prerrequisitos: 'Pensamiento Filosofico',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f812'),
    id: 12,
    nombre: 'Calculo Integral',
    CodigoMateria: 84019,
    Descripcion: 'Fundamentos del cálculo integral y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 602,
    Prerrequisitos: 'Calculo Diferencial',
    PromedioCalificaciones: 3.9
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f815'),
    id: 15,
    nombre: 'Electricidad y Magnetismo',
    CodigoMateria: 84022,
    Descripcion: 'Estudio de los fenómenos eléctricos y magnéticos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 603,
    Prerrequisitos: 'Mecanica',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f818'),
    id: 18,
    nombre: 'Maquinas Electricas',
    CodigoMateria: 84027,
    Descripcion: 'Estudio de máquinas eléctricas y sus aplicaciones en la ingeniería.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 603,
    Prerrequisitos: 'Electricidad y Magnetismo',
    PromedioCalificaciones: 4.9
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f81a'),
    id: 20,
    nombre: 'Interaccion Hombre Maquina',
    CodigoMateria: 84029,
    Descripcion: 'Diseño y evaluación de interfaces entre personas y sistemas computacionales.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 603,
    Prerrequisitos: 'Algoritmos y Programacion 1 y Matematicas Discretas',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f81b'),
    id: 21,
    nombre: 'Probabilidad y Estadistica Descriptiva',
    CodigoMateria: 84030,
    Descripcion: 'Fundamentos de probabilidad y análisis de datos estadísticos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 602,
    Prerrequisitos: 'Metodos Numericos',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f81f'),
    id: 25,
    nombre: 'Electronica Digital',
    CodigoMateria: 84036,
    Descripcion: 'Introducción a los principios de redes de computadoras y su funcionamiento.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 603,
    Prerrequisitos: 'Interaccion Hombre Maquina y Teoria de Bases de datos',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f820'),
    id: 26,
    nombre: 'Procesos de investigacion 1',
    CodigoMateria: 84037,
    Descripcion: 'Gestión y administración de redes informáticas a nivel avanzado.',
    Creditos: 1,
    HorasClase: 144,
    Profesor: 'Wilsón Andrés Castillo Castro',
    Aula: 603,
    Prerrequisitos: 'Redes de Computadores 1',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f822'),
    id: 28,
    nombre: 'Practica de bases de datos',
    CodigoMateria: 84041,
    Descripcion: 'Estudio de los fundamentos y arquitectura de los sistemas operativos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 603,
    Prerrequisitos: 'Algoritmos y Programacion 2',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f826'),
    id: 32,
    nombre: 'Simulacion',
    CodigoMateria: 84045,
    Descripcion: 'Fundamentos y técnicas para el desarrollo de aplicaciones web.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Danny Michael Cardenas Martínez',
    Aula: 603,
    Prerrequisitos: 'Interaccion Hombre Maquina',
    PromedioCalificaciones: 4.6
  },
  {
    _id: ObjectId('66f39f9afa9af32f0942f829'),
    id: 35,
    nombre: 'Construccion de sistemas de informacion',
    CodigoMateria: 84050,
    Descripcion: 'Estudio de las bases de datos distribuidas y su implementación.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 603,
    Prerrequisitos: 'Teoria de Bases de datos',
    PromedioCalificaciones: 4.5
  
  `
    },
    "8": {
        code: `
          _id: ObjectId('66f39fcd19ff2f549c42f807'),
    id: 1,
    nombre: 'Fundamento Matematico',
    CodigoMateria: 84001,
    Descripcion: 'Estudio de los conceptos básicos y fundamentales de las matemáticas.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 206,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f808'),
    id: 2,
    nombre: 'Logica Matematica',
    CodigoMateria: 84002,
    Descripcion: 'Desarrollo del pensamiento lógico y matemático a través de estructuras formales.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 307,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f809'),
    id: 3,
    nombre: 'Algoritmos y Programacion 1',
    CodigoMateria: 84003,
    Descripcion: 'Introducción a la lógica de programación y desarrollo de algoritmos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 601,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f80a'),
    id: 4,
    nombre: 'Lectoescritura Investigativa',
    CodigoMateria: 84005,
    Descripcion: 'Desarrollo de habilidades de lectura crítica y escritura científica.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 308,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f80b'),
    id: 5,
    nombre: 'Algebra Lineal',
    CodigoMateria: 84010,
    Descripcion: 'Estudio de vectores, matrices y espacios vectoriales.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 105,
    Prerrequisitos: 'Logica Matematica',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f80d'),
    id: 7,
    nombre: 'Algoritmos y Programacion 2',
    CodigoMateria: 84012,
    Descripcion: 'Profundización en algoritmos y estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f80e'),
    id: 8,
    nombre: 'Mecanica',
    CodigoMateria: 84013,
    Descripcion: 'Estudio de los principios básicos de la mecánica clásica.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 604,
    Prerrequisitos: 'Introduccion a la ingenieria',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f80f'),
    id: 9,
    nombre: 'Epistemologia Especifica',
    CodigoMateria: 84014,
    Descripcion: 'Reflexión crítica sobre el conocimiento en un campo particular.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 304,
    Prerrequisitos: 'Lectoescritura Investigativa',
    PromedioCalificaciones: 4.6
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f811'),
    id: 11,
    nombre: 'Matematicas Discretas',
    CodigoMateria: 84018,
    Descripcion: 'Estudio de estructuras matemáticas discretas como conjuntos y grafos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 106,
    Prerrequisitos: 'Algebra Lineal',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f813'),
    id: 13,
    nombre: 'Metodos Numericos',
    CodigoMateria: 84020,
    Descripcion: 'Estudio de métodos numéricos para la solución de problemas matemáticos.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 304,
    Prerrequisitos: 'Algebra Lineal',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f814'),
    id: 14,
    nombre: 'Algoritmos y Programacion 3',
    CodigoMateria: 84021,
    Descripcion: 'Avance en la implementación de algoritmos y manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 2 y Algoritmos y Programacion 1',
    PromedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f816'),
    id: 16,
    nombre: 'Etica Profesional',
    CodigoMateria: 84023,
    Descripcion: 'Reflexión sobre la ética en el ejercicio profesional.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 604,
    Prerrequisitos: 'Humanismo Cristiano',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f817'),
    id: 17,
    nombre: 'Ecuaciones Diferenciales',
    CodigoMateria: 84026,
    Descripcion: 'Solución de ecuaciones diferenciales y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 105,
    Prerrequisitos: 'Calculo Diferencial y Calculo Integral',
    PromedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f819'),
    id: 19,
    nombre: 'Estructura De Datos 1',
    CodigoMateria: 84028,
    Descripcion: 'Análisis y diseño de estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1, 2 y 3',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f81c'),
    id: 22,
    nombre: 'Teoria de Bases de datos',
    CodigoMateria: 84033,
    Descripcion: 'Estudio de los principios fundamentales de las bases de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Danny Michael Cardenas Martínez',
    Aula: 604,
    Prerrequisitos: 'Interaccion Hombre Maquina',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f81d'),
    id: 23,
    nombre: 'Estructura de datos 2',
    CodigoMateria: 84034,
    Descripcion: 'Profundización en el manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Estructura de Datos 1',
    PromedioCalificaciones: 4.1
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f81e'),
    id: 24,
    nombre: 'Estadistica Inferencial',
    CodigoMateria: 84035,
    Descripcion: 'Análisis y validación de datos estadísticos mediante técnicas inferenciales.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 105,
    Prerrequisitos: 'Probabilidad y Estadistica Descriptiva',
    PromedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f821'),
    id: 27,
    nombre: 'Formulacion y Gestion de proyectos',
    CodigoMateria: 84038,
    Descripcion: 'Principios y prácticas de seguridad informática.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Wilsón Andrés Castillo Castro',
    Aula: 605,
    Prerrequisitos: 'Redes de Computadores 1',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f823'),
    id: 29,
    nombre: 'Analisis y Modelamiento de Software',
    CodigoMateria: 84042,
    Descripcion: 'Estudio de la estructura interna y funcionamiento de los computadores.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Giovanni Albeiro Hernández Pantoja',
    Aula: 601,
    Prerrequisitos: 'Sistemas Operativos',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f39fcd19ff2f549c42f824'),
    id: 30,
    nombre: 'Arquitectura de Computadores',
    CodigoMateria: 84043,
    Descripcion: 'Uso de modelos matemáticos para la simulación de sistemas complejos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'José Javier Villalba Romero',
    Aula: 604,
    Prerrequisitos: 'Metodos Numericos',
    PromedioCalificaciones: 4.2
  `
    },
    "9": {
        code: `
           _id: ObjectId('66f3a00ae99bc7f36042f814'),
    id: 14,
    nombre: 'Algoritmos y Programacion 3',
    CodigoMateria: 84021,
    Descripcion: 'Avance en la implementación de algoritmos y manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 2 y Algoritmos y Programacion 1',
    PromedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f3a00ae99bc7f36042f819'),
    id: 19,
    nombre: 'Estructura De Datos 1',
    CodigoMateria: 84028,
    Descripcion: 'Análisis y diseño de estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1, 2 y 3',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f3a00ae99bc7f36042f81d'),
    id: 23,
    nombre: 'Estructura de datos 2',
    CodigoMateria: 84034,
    Descripcion: 'Profundización en el manejo de estructuras de datos complejas.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 601,
    Prerrequisitos: 'Estructura de Datos 1',
    PromedioCalificaciones: 4.1
  },
  {
    _id: ObjectId('66f3a00ae99bc7f36042f829'),
    id: 35,
    nombre: 'Construccion de sistemas de informacion',
    CodigoMateria: 84050,
    Descripcion: 'Estudio de las bases de datos distribuidas y su implementación.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Fabian Parra Pay',
    Aula: 603,
    Prerrequisitos: 'Teoria de Bases de datos',
    PromedioCalificaciones: 4.5
  
  `
    },
    "10": {
        code: `
      _id: ObjectId('66f3a0ed6e0001c8ce42f807'),
    id: 1,
    nombre: 'Fundamento Matematico',
    CodigoMateria: 84001,
    Descripcion: 'Estudio de los conceptos básicos y fundamentales de las matemáticas.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 206,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f3a0ed6e0001c8ce42f808'),
    id: 2,
    nombre: 'Logica Matematica',
    CodigoMateria: 84002,
    Descripcion: 'Desarrollo del pensamiento lógico y matemático a través de estructuras formales.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'Leidy Marcela Gómez Melo',
    Aula: 307,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f3a0ed6e0001c8ce42f809'),
    id: 3,
    nombre: 'Algoritmos y Programacion 1',
    CodigoMateria: 84003,
    Descripcion: 'Introducción a la lógica de programación y desarrollo de algoritmos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Juan Sebastián Carrera Bolaños',
    Aula: 601,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f3a0ed6e0001c8ce42f80a'),
    id: 4,
    nombre: 'Lectoescritura Investigativa',
    CodigoMateria: 84005,
    Descripcion: 'Desarrollo de habilidades de lectura crítica y escritura científica.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Neyi Maricela Narvaez Chaves',
    Aula: 308,
    Prerrequisitos: 'Ninguno',
    PromedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f3a0ed6e0001c8ce42f80c'),
    id: 6,
    nombre: 'Calculo Diferencial',
    CodigoMateria: 84011,
    Descripcion: 'Fundamentos del cálculo diferencial y sus aplicaciones.',
    Creditos: 2,
    HorasClase: 96,
    Profesor: 'John Erick Ortíz Guzmán',
    Aula: 603,
    Prerrequisitos: 'Logica Matematica, Fundamento Matematico',
    PromedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f3a0ed6e0001c8ce42f80d'),
    id: 7,
    nombre: 'Algoritmos y Programacion 2',
    CodigoMateria: 84012,
    Descripcion: 'Profundización en algoritmos y estructuras de datos.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Javier Mauricio López Moreno',
    Aula: 601,
    Prerrequisitos: 'Algoritmos y Programacion 1',
    PromedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f3a0ed6e0001c8ce42f80e'),
    id: 8,
    nombre: 'Mecanica',
    CodigoMateria: 84013,
    Descripcion: 'Estudio de los principios básicos de la mecánica clásica.',
    Creditos: 3,
    HorasClase: 144,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 604,
    Prerrequisitos: 'Introduccion a la ingenieria',
    PromedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f3a0ed6e0001c8ce42f80f'),
    id: 9,
    nombre: 'Epistemologia Especifica',
    CodigoMateria: 84014,
    Descripcion: 'Reflexión crítica sobre el conocimiento en un campo particular.',
    Creditos: 1,
    HorasClase: 48,
    Profesor: 'Favio Nicolas Rosero Rodríguez',
    Aula: 304,
    Prerrequisitos: 'Lectoescritura Investigativa',
    PromedioCalificaciones: 4.6
  }
] 

  `
    },
};


// Modal
const modal = document.getElementById("modal");
const modalCode = document.getElementById("modal-code");
const closeModal = document.querySelector(".close");

// Función para abrir el modal
document.querySelectorAll('.view-more-btn').forEach(button => {
    button.addEventListener('click', (e) => {
        const cardId = e.target.getAttribute('data-card');
        
        // Configurar código según la tarjeta
        if (cardId && cardCodeDetails[cardId]) {
            modalCode.textContent = cardCodeDetails[cardId].code;
        }
        
        modal.style.display = "block";
    });
});

// Cerrar modal
closeModal.addEventListener('click', () => {
    modal.style.display = "none";
});
