db.mercado.insertMany([
  { id: 1, nombreProducto: 'arroz', descripcion: 'Arroz del blanco como la nieve ', Precio: 1150, Categoria: 'alimentos', disponibilidad: 23, Marca: 'diana', modelo: 1, peso: 1, unidadesVendidas: 20, valoracionPromedio: 10 },
  { id: 2, nombreProducto: 'Pasta en conchitas', descripcion: 'Pasta la del hombre del bigote', Precio: 4000, Categoria: 'alimentos', disponibilidad: 12, Marca: 'Doria', modelo: 2, peso: 0.25, unidadesVendidas: 9, valoracionPromedio: 8 },
  { id: 3, nombreProducto: 'Spaguetti', descripcion: 'Spaguetti del bambino', Precio: 1090, Categoria: 'alimentos', disponibilidad: 13, Marca: 'Doria', modelo: 3, peso: 1, unidadesVendidas: 13, valoracionPromedio: 10 },
  { id: 4, nombreProducto: 'Cereal', descripcion: 'Cereal la del tigre', Precio: 9250, Categoria: 'alimentos', disponibilidad: 20, Marca: 'Zucaritas ', modelo: 4, peso: 0.42, unidadesVendidas: 20, valoracionPromedio: 6 },
  { id: 5, nombreProducto: 'Fríjol rojo', descripcion: 'Frijol del bueno del puro', Precio: 6750, Categoria: 'alimentos', disponibilidad: 22, Marca: 'La sierra', modelo: 5, peso: 1, unidadesVendidas: 17, valoracionPromedio: 7 },
  { id: 6, nombreProducto: 'Duraznos en almíbar', descripcion: 'Duraznos en almíbar', Precio: 6290, Categoria: 'alimentos', disponibilidad: 10, Marca: 'La coruña', modelo: 6, peso: 0.822, unidadesVendidas: 4, valoracionPromedio: 10 },
  { id: 7, nombreProducto: 'Mantequilla', descripcion: 'Mantequilla de la rica', Precio: 2880, Categoria: 'alimentos', disponibilidad: 14, Marca: 'Alpina', modelo: 7, peso: 0.25, unidadesVendidas: 12, valoracionPromedio: 8 },
  { id: 8, nombreProducto: 'Chocolate', descripcion: 'Chocolate para comer con queso ', Precio: 3780, Categoria: 'alimentos', disponibilidad: 23, Marca: 'corona', modelo: 8, peso: 0.454, unidadesVendidas: 15, valoracionPromedio: 9 },
  { id: 9, nombreProducto: 'Café instantáneo', descripcion: 'Cafe instantáneo', Precio: 8990, Categoria: 'alimentos', disponibilidad: 30, Marca: 'Colcafe', modelo: 9, peso: 0.17, unidadesVendidas: 21, valoracionPromedio: 7 },
  { id: 10, nombreProducto: 'Azúcar blanca', descripcion: ' Azúcar blanca', Precio: 2380, Categoria: 'alimentos', disponibilidad: 34, Marca: 'Manuelita', modelo: 10, peso: 1, unidadesVendidas: 26, valoracionPromedio: 9 },
  { id: 11, nombreProducto: 'Aceite de girasol', descripcion: '1 litro de Aceite', Precio: 7500, Categoria: 'alimentos', disponibilidad: 25, Marca: 'Girasoli', modelo: 11, peso: 1, unidadesVendidas: 12, valoracionPromedio: 7 },
  { id: 12, nombreProducto: 'Sal', descripcion: '1 kilogramo de Sal', Precio: 830, Categoria: 'alimentos', disponibilidad: 37, Marca: 'Refisal', modelo: 12, peso: 1, unidadesVendidas: 35, valoracionPromedio: 10 },
  { id: 13, nombreProducto: 'Huevos AA', descripcion: '30 unidades de huevos', Precio: 8950, Categoria: 'alimentos', disponibilidad: 27, Marca: 'Kike', modelo: 13, peso: 0.06, unidadesVendidas: 16, valoracionPromedio: 8 },
  { id: 14, nombreProducto: 'Leche', descripcion: '900 mililitros de leche', Precio: 12570, Categoria: 'alimentos', disponibilidad: 28, Marca: 'Alqueria', modelo: 14, peso: 0.9, unidadesVendidas: 24, valoracionPromedio: 10 },
  { id: 15, nombreProducto: 'Lentejas', descripcion: '1 kilogramo de Lentejas', Precio: 3950, Categoria: 'alimentos', disponibilidad: 22, Marca: 'Del Costal', modelo: 15, peso: 1, unidadesVendidas: 15, valoracionPromedio: 10 },
  { id: 16, nombreProducto: 'Clorox', descripcion: '1 Litro de cloro', Precio: 2660, Categoria: 'Aseo hogar', disponibilidad: 20, Marca: 'Clorox', modelo: 16, peso: 1, unidadesVendidas: 16, valoracionPromedio: 6 },
  { id: 17, nombreProducto: 'Suavizante', descripcion: '1 litro de suavizante', Precio: 4210, Categoria: 'Aseo hogar', disponibilidad: 15, Marca: 'Fabuloso', modelo: 17, peso: 1, unidadesVendidas: 11, valoracionPromedio: 7 },
  { id: 18, nombreProducto: 'Detergente', descripcion: '3 kilogramo de Detergente', Precio: 18580, Categoria: 'Aseo hogar', disponibilidad: 32, Marca: 'Fab', modelo: 18, peso: 3, unidadesVendidas: 27, valoracionPromedio: 9 },
  { id: 19, nombreProducto: 'Jabón barra', descripcion: '300 gramos de jabón', Precio: 1590, Categoria: 'Aseo hogar', disponibilidad: 17, Marca: 'Fab', modelo: 19, peso: 0.3, unidadesVendidas: 11, valoracionPromedio: 5 },
  { id: 20, nombreProducto: 'Limpiavidrios', descripcion: '500 mililitros de Limpiavidrios', Precio: 6980, Categoria: 'Aseo hogar', disponibilidad: 15, Marca: 'Easy Off ', modelo: 20, peso: 0.5, unidadesVendidas: 9, valoracionPromedio: 10 },
  { id: 21, nombreProducto: 'Shampoo', descripcion: '500 ml de shampoo hidratante', Precio: 15200, Categoria: 'Cuidado personal', disponibilidad: 18, Marca: 'Pantene', modelo: 'Hydra', peso: 0.5, unidadesVendidas: 14, valoracionPromedio: 9 },
  { id: 22, nombreProducto: 'Crema dental', descripcion: '75 ml de crema dental', Precio: 6300, Categoria: 'Cuidado personal', disponibilidad: 30, Marca: 'Colgate', modelo: 'Triple acción', peso: 0.075, unidadesVendidas: 22, valoracionPromedio: 8 },
  { id: 23, nombreProducto: 'Desodorante', descripcion: '50 ml desodorante en barra', Precio: 8900, Categoria: 'Cuidado personal', disponibilidad: 25, Marca: 'Rexona', modelo: 'Sport Defense', peso: 0.05, unidadesVendidas: 16, valoracionPromedio: 9 },
  { id: 24, nombreProducto: 'Toallas higiénicas', descripcion: 'Paquete con 10 toallas', Precio: 4300, Categoria: 'Cuidado personal', disponibilidad: 40, Marca: 'Nosotras', modelo: 'Maxi protección', peso: 0.1, unidadesVendidas: 35, valoracionPromedio: 10 },
  { id: 25, nombreProducto: 'Crema hidratante', descripcion: '200 ml de crema corporal', Precio: 14200, Categoria: 'Cuidado personal', disponibilidad: 10, Marca: 'Nivea', modelo: 'Soft', peso: 0.2, unidadesVendidas: 8, valoracionPromedio: 7 },
  { id: 26, nombreProducto: 'Papel higiénico', descripcion: 'Paquete con 4 rollos', Precio: 12500, Categoria: 'Hogar', disponibilidad: 50, Marca: 'Familia', modelo: 'Ultra suave', peso: 0.5, unidadesVendidas: 45, valoracionPromedio: 9 },
  { id: 27, nombreProducto: 'Foco LED', descripcion: '9W foco LED', Precio: 16000, Categoria: 'Hogar', disponibilidad: 30, Marca: 'Philips', modelo: 'E27', peso: 0.05, unidadesVendidas: 25, valoracionPromedio: 8 },
  { id: 28, nombreProducto: 'Baterías AA', descripcion: 'Paquete de 4 baterías AA', Precio: 8200, Categoria: 'Hogar', disponibilidad: 20, Marca: 'Energizer', modelo: 'Max', peso: 0.1, unidadesVendidas: 15, valoracionPromedio: 7 },
  { id: 29, nombreProducto: 'Sillas plásticas', descripcion: 'Paquete de 2 sillas plásticas', Precio: 19000, Categoria: 'Hogar', disponibilidad: 10, Marca: 'Plastico', modelo: 'Comfort', peso: 2, unidadesVendidas: 5, valoracionPromedio: 6 },
  { id: 30, nombreProducto: 'Mesa plegable', descripcion: 'Mesa de plástico plegable', Precio: 45000, Categoria: 'Hogar', disponibilidad: 5, Marca: 'Plastico', modelo: 'FoldIt', peso: 5, unidadesVendidas: 4, valoracionPromedio: 9 },
  { id: 31, nombreProducto: 'Vasos plásticos', descripcion: 'Paquete de 50 vasos plásticos', Precio: 2500, Categoria: 'Hogar', disponibilidad: 100, Marca: 'Desechables', modelo: 'Económicos', peso: 0.5, unidadesVendidas: 85, valoracionPromedio: 7 },
  { id: 32, nombreProducto: 'Cobija térmica', descripcion: 'Cobija de lana térmica', Precio: 95000, Categoria: 'Hogar', disponibilidad: 3, Marca: 'Lanatex', modelo: 'WarmCozy', peso: 3, unidadesVendidas: 2, valoracionPromedio: 9 },
  { id: 33, nombreProducto: 'Lavadora', descripcion: 'Lavadora automática 12kg', Precio: 1600000, Categoria: 'Electrodomésticos', disponibilidad: 2, Marca: 'LG', modelo: 'TurboDrum', peso: 50, unidadesVendidas: 1, valoracionPromedio: 10 },
  { id: 34, nombreProducto: 'Aspiradora', descripcion: 'Aspiradora de mano', Precio: 320000, Categoria: 'Electrodomésticos', disponibilidad: 6, Marca: 'Black+Decker', modelo: 'Dustbuster', peso: 2.5, unidadesVendidas: 4, valoracionPromedio: 8 },
  { id: 35, nombreProducto: 'Televisor LED', descripcion: 'Televisor LED 55 pulgadas', Precio: 2500000, Categoria: 'Electrónica', disponibilidad: 3, Marca: 'Samsung', modelo: 'SmartTV', peso: 18, unidadesVendidas: 2, valoracionPromedio: 9 },
  { id: 36, nombreProducto: 'Parlante Bluetooth', descripcion: 'Parlante inalámbrico portátil', Precio: 180000, Categoria: 'Electrónica', disponibilidad: 15, Marca: 'JBL', modelo: 'Go 3', peso: 0.2, unidadesVendidas: 10, valoracionPromedio: 10 },
  { id: 37, nombreProducto: 'Cámara de seguridad', descripcion: 'Cámara de seguridad IP', Precio: 350000, Categoria: 'Electrónica', disponibilidad: 7, Marca: 'Hikvision', modelo: 'Dome', peso: 0.3, unidadesVendidas: 5, valoracionPromedio: 9 },
  { id: 38, nombreProducto: 'Mouse inalámbrico', descripcion: 'Mouse óptico inalámbrico', Precio: 35000, Categoria: 'Electrónica', disponibilidad: 50, Marca: 'Logitech', modelo: 'M170', peso: 0.1, unidadesVendidas: 40, valoracionPromedio: 8 },
  { id: 39, nombreProducto: 'Teclado mecánico', descripcion: 'Teclado gamer mecánico RGB', Precio: 250000, Categoria: 'Electrónica', disponibilidad: 10, Marca: 'Redragon', modelo: 'K552', peso: 1, unidadesVendidas: 8, valoracionPromedio: 9 },
  { id: 40, nombreProducto: 'Memoria USB', descripcion: 'Memoria USB 64GB', Precio: 60000, Categoria: 'Electrónica', disponibilidad: 25, Marca: 'SanDisk', modelo: 'Ultra', peso: 0.02, unidadesVendidas: 22, valoracionPromedio: 9 }
]);
//db.mercado.find({ nombreProducto: { $eq: 'arroz' } }); //1// encontrar un solo producto en el mercado 
//db.mercado.find({ Precio: { $gt: 8000 } });//2//encontrar los productos que valen mas de 9000
//db.mercado.find({ disponibilidad: { $gte: 25 } }); //3// encontrar los productos que tengan 25 o mas disponibles
//db.mercado.find({ modelo: { $lt: 5 } }); //4//encontrar los productos que tengan un modelo menor a 5
//db.mercado.find({ peso: { $lte: 2 } });//5//encontrar losproductos tengan un peso menor o igual a 2 kilogramos
//db.mercado.find({ unidadesVendidas: { $ne: 10 } });//6//encontrar los productos cuyas unidades vendidas sea diferente de 10
//db.mercado.find({ valoracionPromedio: { $in: [8,9,10] } });//7//encontrar los productos cuya valoracion este entre 8 y 10
//db.mercado.find({ valoracionPromedio: { $nin: [8,9,10] } });//8//encontrar los productos cuya valoracion no este entre 8 y 10
//db.mercado.find({$and: [{ Precio: { $gt: 9000 } },{ unidadesVendidas: { $gt: 25 } }]}); //9//encontrar los productos que tengan un precio mayor a 9000 y tenga mas de 25 unidades vendidas
//db.mercado.updateOne({ id: 1 },{ $set: { descripcion: 'Nuevo arroz de calidad superior' } });//10/Actualiza un producto con id 1
//db.mercado.find({id:{$lte:1}})                                                                //10/mostrar solo el primer elemento y ya se mira que se edito la descripcion