db.materias.insertMany([
{ id: 1, nombre:'Fundamento Matematico', CodigoMateria: 84001, Descripcion:'Estudio de los conceptos básicos y fundamentales de las matemáticas.', Creditos: 2, HorasClase: 96, Profesor: 'Leidy Marcela Gómez Melo', Aula: 206, Prerrequisitos:'Ninguno', PromedioCalificaciones: 4.5},
{ id: 2, nombre:'Logica Matematica', CodigoMateria: 84002, Descripcion:'Desarrollo del pensamiento lógico y matemático a través de estructuras formales.', Creditos: 2, HorasClase: 96, Profesor: 'Leidy Marcela Gómez Melo', Aula: 307, Prerrequisitos:'Ninguno', PromedioCalificaciones: 4.8},
{ id: 3, nombre:'Algoritmos y Programacion 1', CodigoMateria: 84003, Descripcion:'Introducción a la lógica de programación y desarrollo de algoritmos.', Creditos: 3, HorasClase: 144, Profesor: 'Juan Sebastián Carrera Bolaños', Aula: 601, Prerrequisitos:'Ninguno', PromedioCalificaciones: 4.8},
{ id: 4, nombre:'Lectoescritura Investigativa', CodigoMateria: 84005, Descripcion:'Desarrollo de habilidades de lectura crítica y escritura científica.', Creditos: 1, HorasClase: 48, Profesor: 'Neyi Maricela Narvaez Chaves', Aula: 308, Prerrequisitos:'Ninguno', PromedioCalificaciones: 4.2},
{ id: 5, nombre:'Algebra Lineal', CodigoMateria: 84010, Descripcion:'Estudio de vectores, matrices y espacios vectoriales.', Creditos: 2, HorasClase: 96, Profesor: 'John Erick Ortíz Guzmán', Aula: 105, Prerrequisitos:'Logica Matematica', PromedioCalificaciones: 4.5},
{ id: 6, nombre:'Calculo Diferencial', CodigoMateria: 84011, Descripcion:'Fundamentos del cálculo diferencial y sus aplicaciones.', Creditos: 2, HorasClase: 96, Profesor: 'John Erick Ortíz Guzmán', Aula: 603, Prerrequisitos:'Logica Matematica, Fundamento Matematico', PromedioCalificaciones: 3.5},
{ id: 7, nombre:'Algoritmos y Programacion 2', CodigoMateria: 84012, Descripcion:'Profundización en algoritmos y estructuras de datos.', Creditos: 3, HorasClase: 144, Profesor:'Javier Mauricio López Moreno', Aula: 601, Prerrequisitos:'Algoritmos y Programacion 1', PromedioCalificaciones: 4.3},
{ id: 8, nombre:'Mecanica', CodigoMateria: 84013, Descripcion:'Estudio de los principios básicos de la mecánica clásica.', Creditos: 3, HorasClase: 144, Profesor: 'Favio Nicolas Rosero Rodríguez', Aula: 604, Prerrequisitos:'Introduccion a la ingenieria', PromedioCalificaciones: 4.5},
{ id: 9, nombre:'Epistemologia Especifica', CodigoMateria: 84014, Descripcion:'Reflexión crítica sobre el conocimiento en un campo particular.', Creditos: 1, HorasClase: 48, Profesor: 'Favio Nicolas Rosero Rodríguez', Aula: 304, Prerrequisitos:'Lectoescritura Investigativa', PromedioCalificaciones: 4.6},
{ id: 10, nombre:'Humanismo Cristiano', CodigoMateria: 84015, Descripcion:'Estudio de los valores y principios del humanismo cristiano.', Creditos: 2, HorasClase: 96, Profesor: 'Neyi Maricela Narvaez Chaves', Aula: 603, Prerrequisitos:'Pensamiento Filosofico', PromedioCalificaciones: 4.5},
{ id: 11, nombre:'Matematicas Discretas', CodigoMateria: 84018, Descripcion:'Estudio de estructuras matemáticas discretas como conjuntos y grafos.', Creditos: 2, HorasClase: 96, Profesor:'Javier Mauricio López Moreno', Aula: 106, Prerrequisitos:'Algebra Lineal', PromedioCalificaciones: 3.5},
{ id: 12, nombre:'Calculo Integral', CodigoMateria: 84019, Descripcion:'Fundamentos del cálculo integral y sus aplicaciones.', Creditos: 2, HorasClase: 96, Profesor:'John Erick Ortíz Guzmán', Aula: 602, Prerrequisitos:'Calculo Diferencial', PromedioCalificaciones: 3.9},
{ id: 13, nombre:'Metodos Numericos', CodigoMateria: 84020, Descripcion:'Estudio de métodos numéricos para la solución de problemas matemáticos.', Creditos: 2, HorasClase: 96, Profesor: 'John Erick Ortíz Guzmán', Aula: 304, Prerrequisitos:'Algebra Lineal', PromedioCalificaciones: 4.5},
{ id: 14, nombre:'Algoritmos y Programacion 3', CodigoMateria: 84021, Descripcion:'Avance en la implementación de algoritmos y manejo de estructuras de datos complejas.', Creditos: 3, HorasClase: 144, Profesor: 'Fabian Parra Pay', Aula: 601, Prerrequisitos:'Algoritmos y Programacion 2 y Algoritmos y Programacion 1', PromedioCalificaciones: 4.0},
{ id: 15, nombre:'Electricidad y Magnetismo', CodigoMateria: 84022, Descripcion:'Estudio de los fenómenos eléctricos y magnéticos.', Creditos: 2, HorasClase: 96, Profesor: 'Favio Nicolas Rosero Rodríguez', Aula: 603, Prerrequisitos:'Mecanica', PromedioCalificaciones: 4.3},
{ id: 16, nombre:'Etica Profesional', CodigoMateria: 84023, Descripcion:'Reflexión sobre la ética en el ejercicio profesional.', Creditos: 2, HorasClase: 96, Profesor: 'Neyi Maricela Narvaez Chaves', Aula: 604, Prerrequisitos:'Humanismo Cristiano', PromedioCalificaciones: 4.7},
{ id: 17, nombre:'Ecuaciones Diferenciales', CodigoMateria: 84026, Descripcion:'Solución de ecuaciones diferenciales y sus aplicaciones.', Creditos: 2, HorasClase: 96, Profesor:'Leidy Marcela Gómez Melo', Aula: 105, Prerrequisitos:'Calculo Diferencial y Calculo Integral', PromedioCalificaciones: 4.7},
{ id: 18, nombre:'Maquinas Electricas', CodigoMateria: 84027, Descripcion:'Estudio de máquinas eléctricas y sus aplicaciones en la ingeniería.', Creditos: 3, HorasClase: 144, Profesor: 'José Javier Villalba Romero', Aula: 603, Prerrequisitos:'Electricidad y Magnetismo', PromedioCalificaciones: 4.9},
{ id: 19, nombre:'Estructura De Datos 1', CodigoMateria: 84028, Descripcion:'Análisis y diseño de estructuras de datos.', Creditos: 3, HorasClase: 144, Profesor: 'Fabian Parra Pay', Aula: 601, Prerrequisitos:'Algoritmos y Programacion 1, 2 y 3', PromedioCalificaciones: 4.2},
{ id: 20, nombre:'Interaccion Hombre Maquina', CodigoMateria: 84029, Descripcion:'Diseño y evaluación de interfaces entre personas y sistemas computacionales.', Creditos: 3, HorasClase: 144, Profesor:'Javier Mauricio López Moreno', Aula: 603, Prerrequisitos:'Algoritmos y Programacion 1 y Matematicas Discretas', PromedioCalificaciones: 4.7},
{ id: 21, nombre:'Probabilidad y Estadistica Descriptiva', CodigoMateria: 84030, Descripcion:'Fundamentos de probabilidad y análisis de datos estadísticos.', Creditos: 3, HorasClase: 144, Profesor: 'Leidy Marcela Gómez Melo', Aula: 602, Prerrequisitos:'Metodos Numericos', PromedioCalificaciones: 4.4},
{ id: 22, nombre:'Teoria de Bases de datos', CodigoMateria: 84033, Descripcion:'Estudio de los principios fundamentales de las bases de datos.', Creditos: 3, HorasClase: 144, Profesor:'Danny Michael Cardenas Martínez', Aula: 604, Prerrequisitos:'Interaccion Hombre Maquina', PromedioCalificaciones: 4.4},
{ id: 23, nombre:'Estructura de datos 2', CodigoMateria: 84034, Descripcion:'Profundización en el manejo de estructuras de datos complejas.', Creditos: 3, HorasClase: 144, Profesor: 'Fabian Parra Pay', Aula: 601, Prerrequisitos:'Estructura de Datos 1', PromedioCalificaciones: 4.1},
{ id: 24, nombre:'Estadistica Inferencial', CodigoMateria: 84035, Descripcion:'Análisis y validación de datos estadísticos mediante técnicas inferenciales.', Creditos: 3, HorasClase: 144, Profesor: 'Leidy Marcela Gómez Melo', Aula: 105, Prerrequisitos:'Probabilidad y Estadistica Descriptiva', PromedioCalificaciones: 4.4},
{ id: 25, nombre:'Electronica Digital', CodigoMateria: 84036, Descripcion:'Introducción a los principios de redes de computadoras y su funcionamiento.', Creditos: 3, HorasClase: 144, Profesor:'José Javier Villalba Romero', Aula: 603, Prerrequisitos:'Interaccion Hombre Maquina y Teoria de Bases de datos', PromedioCalificaciones: 4.7},
{ id: 26, nombre:'Procesos de investigacion 1', CodigoMateria: 84037, Descripcion:'Gestión y administración de redes informáticas a nivel avanzado.', Creditos: 1, HorasClase: 144, Profesor:'Wilsón Andrés Castillo Castro', Aula: 603, Prerrequisitos:'Redes de Computadores 1', PromedioCalificaciones: 4.3},
{ id: 27, nombre:'Formulacion y Gestion de proyectos', CodigoMateria: 84038, Descripcion:'Principios y prácticas de seguridad informática.', Creditos: 3, HorasClase: 144, Profesor: 'Wilsón Andrés Castillo Castro', Aula: 605, Prerrequisitos:'Redes de Computadores 1', PromedioCalificaciones: 4.5},
{ id: 28, nombre:'Practica de bases de datos', CodigoMateria: 84041, Descripcion:'Estudio de los fundamentos y arquitectura de los sistemas operativos.', Creditos: 3, HorasClase: 144, Profesor:'Juan Sebastián Carrera Bolaños', Aula: 603, Prerrequisitos:'Algoritmos y Programacion 2', PromedioCalificaciones: 4.3},
{ id: 29, nombre:'Analisis y Modelamiento de Software', CodigoMateria: 84042, Descripcion:'Estudio de la estructura interna y funcionamiento de los computadores.', Creditos: 3, HorasClase: 144, Profesor:'Giovanni Albeiro Hernández Pantoja', Aula: 601, Prerrequisitos:'Sistemas Operativos', PromedioCalificaciones: 4.5},
{ id: 30, nombre:'Arquitectura de Computadores', CodigoMateria: 84043, Descripcion:'Uso de modelos matemáticos para la simulación de sistemas complejos.', Creditos: 3, HorasClase: 144, Profesor: 'José Javier Villalba Romero', Aula: 604, Prerrequisitos:'Metodos Numericos', PromedioCalificaciones: 4.2},
{ id: 31, nombre:'Sistemas Operativos', CodigoMateria: 84044, Descripcion:'Principios, métodos y herramientas para la ingeniería de software.', Creditos: 3, HorasClase: 144, Profesor:'Wilsón Andrés Castillo Castro', Aula: 601, Prerrequisitos:'Algoritmos y Programacion 3', PromedioCalificaciones: 4.4},
{ id: 32, nombre:'Simulacion', CodigoMateria: 84045, Descripcion:'Fundamentos y técnicas para el desarrollo de aplicaciones web.', Creditos: 3, HorasClase: 144, Profesor: 'Danny Michael Cardenas Martínez', Aula: 603, Prerrequisitos:'Interaccion Hombre Maquina', PromedioCalificaciones: 4.6},
{ id: 33, nombre:'Procesos de Investigacion 2', CodigoMateria: 84046, Descripcion:'Principios y técnicas del desarrollo de videojuegos.', Creditos: 1, HorasClase: 144, Profesor:'Wilsón Andrés Castillo Castro', Aula: 604, Prerrequisitos:'Interaccion Hombre Maquina', PromedioCalificaciones: 4.5},
{ id: 34, nombre:'Vision Empresarial', CodigoMateria: 84047, Descripcion:'Estudio y aplicación de técnicas gráficas computacionales.', Creditos: 1, HorasClase: 144, Profesor:'Jorge Arturo Dorado Goyes', Aula: 601, Prerrequisitos:'Algoritmos y Programacion 3', PromedioCalificaciones: 4.6},
{ id: 35, nombre:'Construccion de sistemas de informacion', CodigoMateria: 84050, Descripcion:'Estudio de las bases de datos distribuidas y su implementación.', Creditos: 3, HorasClase: 144, Profesor: 'Fabian Parra Pay', Aula: 603, Prerrequisitos:'Teoria de Bases de datos', PromedioCalificaciones: 4.5},
{ id: 36, nombre:'Ingenieria de Software', CodigoMateria: 84051, Descripcion:'Introducción a los principios y aplicaciones de la robótica.', Creditos: 3, HorasClase: 144, Profesor: 'Giovanni Albeiro Hernández Pantoja', Aula: 604, Prerrequisitos:'Algoritmos y Programacion 3', PromedioCalificaciones: 4.7},
{ id: 37, nombre:'Seminario de Investigacion', CodigoMateria: 84052, Descripcion:'Estudio de sistemas embebidos y sus aplicaciones.', Creditos: 1, HorasClase: 144, Profesor:'Wilsón Andrés Castillo Castro', Aula: 605, Prerrequisitos:'Arquitectura de Computadores', PromedioCalificaciones: 4.8},
{ id: 38, nombre:'Legislacion Laboral', CodigoMateria: 84053, Descripcion:'Fundamentos y aplicaciones de la inteligencia artificial.', Creditos: 3, HorasClase: 144, Profesor:'José Javier Villalba Romero', Aula: 601, Prerrequisitos:'Algoritmos y Programacion 3', PromedioCalificaciones: 4.6},
{ id: 39, nombre:'Pilares del Espiritu Empresarial', CodigoMateria: 84054, Descripcion:'Introducción a las tecnologías y métodos del análisis de big data.', Creditos: 1, HorasClase: 144, Profesor:'Jorge Arturo Dorado Goyes', Aula: 604, Prerrequisitos:'Bases de datos distribuidas', PromedioCalificaciones: 4.6},
{ id: 40, nombre:'Ingenieria de Software 2', CodigoMateria: 84058, Descripcion:'Estudio de los principios y tecnologías para la computación en la nube.', Creditos: 2, HorasClase: 144, Profesor: 'Juan Carlos Portilla Salas', Aula: 605, Prerrequisitos:'Redes de Computadores 1', PromedioCalificaciones: 4.7}
]);
//db.materias.find({ nombre: { $eq: 'Algoritmos y Programacion 1' } }); //1// Busca la materia cuyo nombre es igual a Algoritmos y Programacion 1
//db.materias.find({ Creditos: { $gt: 2 } });//2// Busca las materias que sean de más de 2 créditos
//db.materias.find({ HorasClase: { $gte: 96 } });//3// Busca las materias con 96 horas de clase teóricas o mas 
//db.materias.find({ HorasClase: { $lt: 96 } }); //4// Busca las materias con menos de 96 horas de clase teóricas 
//db.materias.find({ CodigoMateria: { $lte: 84020 } }); //5// Busca las materias cuyo código sea menor o igual a 84020
//db.materias.find({ Profesor: { $ne: 'Leidy Marcela Gómez Melo' } }); //6// Busca las materias que no son brindadas por la profe Leidy Marcela Gómez Melo
//db.materias.find({ Aula: { $in: [602, 603] } }); //7// Busca las materias que se dan en los salones 602 y 603
//db.materias.find({ Aula: { $nin: [602, 603] } }); //8//  Busca las materias que se den en los salones 602 y 603
//db.materias.find({$and: [{ Creditos: { $gt: 2 } },{ Profesor: { $eq: 'Fabian Parra Pay' } }]}); //9// Busca todas las materias que tienen más de 2 créditos y cuyo profesor sea Fabian Parra 
//db.materias.deleteOne({ id: 5 }); //10// Elimina la materia con el id 5
//db.materias.find({ id: { $lt: 10 } });